# Generated by Django 2.1.3 on 2018-11-20 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='versions',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
